version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: csdb
      POSTGRES_USER: csuser
      POSTGRES_PASSWORD: cspass

  web:
    build:
      context: ./CSbackend
      dockerfile: Dockerfile
    command: gunicorn CSbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./CSbackend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=ul6v3gtio3_&m&%oelcb6(+t=-fbj2ovv(9-8+8ekta(sjtxc&
      - DATABASE_URL=postgres://csuser:cspass@db:5432/csdb
      - DEBUG=1

  frontend:
    build:
      context: ./csfrontend
      dockerfile: Dockerfile
    volumes:
      - ./csfrontend:/app
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
