# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: csdb
      POSTGRES_USER: csuser
      POSTGRES_PASSWORD: cspass

  web:
    build: .
    command: gunicorn CSbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./CSbackend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - DEBUG=1

  frontend:
    build:
      context: ./csfrontend
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
