# Generated by Django 5.1 on 2024-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='special_link',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
